

# Run `kubectl apply -f vpc.yaml` to test this example once you bootstrap the EKS cluster with Crossplane and AWS Provider
---
apiVersion: network.awsblueprints.io/v1alpha1
kind: amazonVpc
metadata:
  name: xplane-amazon-vpc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "30" 
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      service: vpc
      compute: managedamazon-vpc
  resourceConfig:
    providerConfigName: default
    region: eu-west-2
  parameters:
    vpcName: aws-provider-vpc
    vpccidrBlock: "192.168.1.0/24"
    amazonProvidedIpv6CidrBlock: false
